[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
node_string_saver = "4BURzfAxaZbwk8HwBmbo3U7yQYu4Zok9bttGuXjkkWvq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
